name: note_app
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # use svg images in this project
  flutter_svg: ^1.1.4
  # additional features for this project
  intl: ^0.17.0
  # package for isolate that can allow to run some codes on another thread
  flutter_isolate: ^2.0.2
  # Hive database to save all information locally
  hive: ^2.2.3
  provider: 6.0.3
  path_provider: 2.0.11
  # Bottom Modal sheet to show extra menus
  modal_bottom_sheet: ^2.0.0
  # State management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  # To take photos from storage
  image_picker: ^0.8.5+3
  
  # ring draw a rectangle using lines
  dotted_border: ^2.0.0+2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Inter-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Inter-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Inter-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Inter-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/Inter-Thin.ttf
          weight: 100
          style: normal

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
